site_name: GLFW Inputs
theme:
  name: 'material'
nav:
  - Home: index.md
  - Installation:
    - With CMake: getting-started/installation-cmake.md
    - Include in project: getting-started/installation-file.md
  - Getting started:
    - Architecture: architecture/architecture.md
    - Basic usage: getting-started/basic-usage.md
    - Button down states: getting-started/button-down-states.md
    - Motion controls: getting-started/motion-controls.md
    - Swapping mappings: getting-started/swapping-mappings.md
  - Controls:
    - Keyboard: controls/keyboard.md
    - Mouse: controls/mouse.md
    - Joystick: controls/joystick.md
  - Appendices:
    - List of inputs: misc/enums-inputs.md
    - List of events: misc/events.md
    - MotionEvent: misc/motion-event.md
    - MotionSurface: misc/motion-surface.md
    - Position: misc/position.md